name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "your_database_name"  # 替换为你创建的数据库名称
database_id = "your_database_id"      # 替换为你创建的数据库 ID
